- Editor/src/Ouroboros/API/AnimationAPI.h
- Editor/src/Ouroboros/Animation/Anim_Utils.cpp
- Editor/src/Ouroboros/Animation/Anim_Utils.h
- Editor/src/Ouroboros/Animation/Animation.cpp
- Editor/src/Ouroboros/Animation/Animation.h
- Editor/src/Ouroboros/Animation/AnimationComponent.cpp
- Editor/src/Ouroboros/Animation/AnimationComponent.h
- Editor/src/Ouroboros/Animation/AnimationInternal.cpp
- Editor/src/Ouroboros/Animation/AnimationInternal.h
- Editor/src/Ouroboros/Animation/AnimationKeyFrame.cpp
- Editor/src/Ouroboros/Animation/AnimationKeyFrame.h
- Editor/src/Ouroboros/Animation/AnimationSystem.cpp
- Editor/src/Ouroboros/Animation/AnimationSystem.h
- Editor/src/Ouroboros/Animation/AnimationTimeline.cpp
- Editor/src/Ouroboros/Animation/AnimationTimeline.h
- Editor/src/Ouroboros/Animation/AnimationTree.cpp
- Editor/src/Ouroboros/Animation/AnimationTree.h
- Editor/vendor/scriptcore/src/ScriptCore/Components/Animation.cs
animation deserializaiton done
added set animation function
animation system now can add new animations
> anim updates

- Editor/src/Ouroboros/Scripting/ScriptSystem.cpp
fixed engine crashing if there is collision/trigger with no scripts in the project
> Quick Bug Fix

- Editor/src/App/Editor/UI/Object Editor/EditorViewport.cpp
- Editor/src/Ouroboros/Scene/EditorController.h
- Editor/src/Ouroboros/Scene/Scene.cpp
- Editor/src/Ouroboros/Vulkan/RendererSystem.cpp
- Editor/src/Ouroboros/Vulkan/VulkanContext.cpp
- Editor/vendor/vulkan/OO_Vulkan/imgui.ini
- Editor/vendor/vulkan/OO_Vulkan/shaders/deferredlighting.frag
- Editor/vendor/vulkan/OO_Vulkan/shaders/gbuffer.frag
- Editor/vendor/vulkan/OO_Vulkan/shaders/gbuffer.vert
- Editor/vendor/vulkan/OO_Vulkan/src/Camera.h
- Editor/vendor/vulkan/OO_Vulkan/src/DebugDraw.cpp
- Editor/vendor/vulkan/OO_Vulkan/src/DefaultMeshCreator.cpp
- Editor/vendor/vulkan/OO_Vulkan/src/GfxRenderpass.h
- Editor/vendor/vulkan/OO_Vulkan/src/GraphicsWorld.h
- Editor/vendor/vulkan/OO_Vulkan/src/VulkanRenderer.cpp
- Editor/vendor/vulkan/OO_Vulkan/src/VulkanRenderer.h
- Editor/vendor/vulkan/OO_Vulkan/src/VulkanSwapchain.cpp
- Editor/vendor/vulkan/OO_Vulkan/src/VulkanTexture.cpp
- Editor/vendor/vulkan/OO_Vulkan/src/VulkanUtils.cpp
- Editor/vendor/vulkan/OO_Vulkan/src/VulkanUtils.h
- Editor/vendor/vulkan/OO_Vulkan/src/renderpass/DebugRenderpass.cpp
- Editor/vendor/vulkan/OO_Vulkan/src/renderpass/DeferredCompositionRenderpass.cpp
- Editor/vendor/vulkan/OO_Vulkan/src/renderpass/GBufferRenderPass.cpp
- Editor/vendor/vulkan/OO_Vulkan/src/renderpass/ShadowPass.cpp
- Editor/vendor/vulkan/OO_Vulkan/src/rhi/CommandList.cpp
#183 maybe fixes this issue @JunXiang-Leong
> Maybe viewport one day

- Editor/src/Ouroboros/Animation/Animation.cpp
- Editor/src/Ouroboros/Animation/Animation.h
- Editor/src/Ouroboros/Animation/AnimationInternal.cpp
- Editor/src/Ouroboros/Animation/AnimationKeyFrame.cpp
- Editor/src/Ouroboros/Animation/AnimationTimeline.cpp
fbx filename appended as prefix to loaded animation name 
animation timeline serialization & loading bugfixes 
animation keyframe serialization quaternion bugfixes
> animation bugfixes & improvements

- Editor/src/Ouroboros/Animation/AnimationInternal.cpp
basically handles cases like when animation tree is invalid or not assigned
> bugfixes for animation stuffs

- Editor/src/Ouroboros/Scene/Scene.cpp
- Editor/src/Ouroboros/Scene/Scene.h
- Editor/vendor/vulkan/OO_Vulkan/src/GraphicsWorld.h
- Editor/vendor/vulkan/OO_Vulkan/src/VulkanRenderer.cpp
- Editor/vendor/vulkan/OO_Vulkan/src/VulkanRenderer.h
- Editor/vendor/vulkan/OO_Vulkan/src/renderpass/DebugRenderpass.cpp
- Editor/vendor/vulkan/OO_Vulkan/src/renderpass/DeferredCompositionRenderpass.cpp
> Bugfix graphics world

- Editor/vendor/vulkan/OO_Vulkan/src/VulkanRenderer.cpp
can delete branch after merging
> fixed warnings & updated submodule

- Editor/src/Ouroboros/Animation/AnimationInternal.cpp
- Editor/src/Ouroboros/Scene/RuntimeScene.cpp
bindphase of animation system runs in correct order now
> some additional checks and animation fix

- Editor/src/App/Editor/UI/Object Editor/FileBrowser.cpp
- Editor/src/App/Editor/UI/Tools/AnimatorControllerView.cpp
- Editor/src/Ouroboros/Animation/Anim.cpp
- Editor/src/Ouroboros/Animation/Anim_Utils.h
- Editor/src/Ouroboros/Animation/AnimationComponent.cpp
- Editor/src/Ouroboros/Animation/AnimationComponent.h
- Editor/src/Ouroboros/Animation/AnimationInternal.cpp
- Editor/src/Ouroboros/Animation/AnimationInternal.h
- Editor/src/Ouroboros/Animation/AnimationSystem.cpp
- Editor/src/Ouroboros/Animation/AnimationSystem.h
- Editor/src/Ouroboros/Animation/AnimationTimeline.cpp
- Editor/src/Ouroboros/Animation/AnimationTree.cpp
- Editor/src/Ouroboros/Animation/AnimationTree.h
anim tree for animation component set via asset
reinsert keyframe functionality for the timeline functionality
> animation updates

- Editor/src/Ouroboros/Vulkan/VulkanContext.cpp
- Editor/vendor/vulkan/OO_Vulkan/shaders/deferredlighting.frag
- Editor/vendor/vulkan/OO_Vulkan/shaders/deferredlighting.vert
- Editor/vendor/vulkan/OO_Vulkan/shaders/frame.shader
- Editor/vendor/vulkan/OO_Vulkan/shaders/gbuffer.frag
- Editor/vendor/vulkan/OO_Vulkan/shaders/shared_structs.h
- Editor/vendor/vulkan/OO_Vulkan/src/Camera.cpp
- Editor/vendor/vulkan/OO_Vulkan/src/GfxRenderpass.h
- Editor/vendor/vulkan/OO_Vulkan/src/GfxSampler.cpp
- Editor/vendor/vulkan/OO_Vulkan/src/GfxSampler.h
- Editor/vendor/vulkan/OO_Vulkan/src/GpuVector.h
- Editor/vendor/vulkan/OO_Vulkan/src/GraphicsWorld.h
- Editor/vendor/vulkan/OO_Vulkan/src/VulkanRenderer.cpp
- Editor/vendor/vulkan/OO_Vulkan/src/VulkanRenderer.h
- Editor/vendor/vulkan/OO_Vulkan/src/renderpass/DebugRenderpass.cpp
- Editor/vendor/vulkan/OO_Vulkan/src/renderpass/DeferredCompositionRenderpass.cpp
- Editor/vendor/vulkan/OO_Vulkan/src/renderpass/GBufferRenderPass.cpp
- Editor/vendor/vulkan/OO_Vulkan/src/renderpass/ShadowPass.cpp
@DeveloperSolo  sir pls help test as the IMGD sacrifice
> Shadows for first light in the light array lol

- Editor/src/App/Editor/UI/Tools/AnimatorControllerView.cpp
- Animator Controller Nodes can now be draggable after bugfix
> Added bugfix for the Animator Controller GUI

- Editor/src/Ouroboros/API/ApplicationAPI.h
- Editor/vendor/scriptcore/src/ScriptCore/Data/Asset.cs
- Editor/vendor/scriptcore/src/ScriptCore/Data/AudioClip.cs
- Editor/vendor/scriptcore/src/ScriptCore/Data/Texture.cs
- Editor/vendor/scriptcore/src/ScriptCore/Libraries/Application.cs
- ability to get assets by type (Asset.GetByType, or AudioClip.GetAll)
- ability to get path to asset folder
> Requested Scripting Features

- Editor/src/Ouroboros/API/GameObjectAPI.h
- Editor/vendor/scriptcore/src/ScriptCore/Object.cs
in C#, its Instantiate(GameObject original, Transform parent)
> Added C# Duplicate

- Editor/src/App/Editor/Properties/SerializerProperties.cpp
- Editor/src/App/Editor/Serializer.cpp
- Editor/src/App/Editor/UI/Object Editor/Inspector.cpp
- Editor/src/App/Editor/UI/Tools/AnimatorControllerView.cpp
- Editor/src/App/Editor/UI/Tools/MeshHierarchy.cpp
- Editor/src/Ouroboros/Animation/Animation.cpp
- Editor/src/Ouroboros/Animation/Animation.h
- Editor/src/Ouroboros/Animation/AnimationInternal.cpp
- Editor/src/Ouroboros/Animation/AnimationInternal.h
- Editor/src/Ouroboros/Animation/AnimationSystem.cpp
- Editor/src/Ouroboros/Animation/AnimationSystem.h
- Editor/src/Ouroboros/Commands/ActionCommandHelper.cpp
- Editor/src/Ouroboros/Scene/EditorScene.cpp
- Editor/src/Ouroboros/Scene/RuntimeScene.cpp
- Editor/src/Ouroboros/Scene/Scene.cpp
- Editor/src/Ouroboros/Vulkan/SkinRendererComponent.cpp
- Editor/src/Ouroboros/Vulkan/SkinRendererComponent.h
- Editor/src/Ouroboros/Vulkan/SkinRendererSystem.cpp
- Editor/src/Ouroboros/Vulkan/SkinRendererSystem.h
- Editor/vendor/vulkan/OO_Vulkan/src/VulkanRenderer.cpp
set bone components graphics world id after loading objects in scene
fbx serializing and rendering fixes
made some debug prints toggle-able to shorten load time
no longer crashes upon loading scene with skin mesh
added toggleable debug print for some other things
fixed keyframe index not updating correctly
TLDR: I guess skin meshes can actually move properly now
U can use my branch on the game prototype's git at GH/anim-test for a project to see the character moving
> animation major updates

- Editor/src/Ouroboros/API/PhysicsAPI.h
solution feels incredibly scuffed but it works
> Fixed C# RaycastAll data passing

- Editor/src/Ouroboros/Vulkan/SkinRendererSystem.cpp
- Editor/src/Ouroboros/Vulkan/SkinRendererSystem.h
> duplicate skin mesh gameobjects work

- Editor/src/App/CoreLayers/ScriptingLayer.h
- Editor/src/Ouroboros/API/ParticleEmitterAPI.h
- Editor/src/Ouroboros/API/PhysicsAPI.h
- Editor/src/Ouroboros/API/RigidbodyAPI.h
- Editor/src/Ouroboros/Scripting/ScriptInfo.cpp
- Editor/vendor/scriptcore/src/ScriptCore/Components/Rigidbody.cs
- added comments
- fixed static variables not reset when stop/start play
- changed C# Rigidbody.gravityDisabled to Rigidbody.useGravity to better match what it actually does
(for the last one, will have CTE if used to open Minute, lemme know once a new engine installer is made so i can push changes to Minute)
> bug fixes + comments

- Editor/src/Ouroboros/API/ApplicationAPI.h
- Editor/src/Ouroboros/API/DebugAPI.h
- Editor/src/Ouroboros/API/MainAPI.cpp
- Editor/src/Ouroboros/Scripting/ScriptValue.h
- Editor/vendor/scriptcore/src/ScriptCore/Libraries/Debug.cs
- DrawLine
- DrawWireCube
- DrawWireSphere
- DrawArrow
> C# Debug Draw Functions

- Editor/src/App/Editor/UI/Tools/AnimatorControllerView.cpp
- Editor/src/Ouroboros/Animation/AnimationCondition.cpp
- Editor/src/Ouroboros/Animation/AnimationSystem.cpp
- Editor/src/Ouroboros/Vulkan/SkinRendererSystem.cpp
- Editor/src/Ouroboros/Vulkan/SkinRendererSystem.h
- Editor/vendor/vulkan/OO_Vulkan/src/VulkanRenderer.cpp
generate condition uid when being added via editor
assigned all bone components their corresponding game object uid
wip
probably works
> anims work with prefabs

- Editor/src/App/Editor/UI/Object Editor/EditorViewport.cpp
- Editor/src/Ouroboros/Transform/TransformSystem.cpp
- Editor/src/Ouroboros/Transform/TransformSystem.h
- Editor/src/Ouroboros/UI/UISystem.cpp
There's also a big bug for transform that is fixed here!
> Bugfix UI raycast [Please Delete branch after merge!]

- Editor/src/Ouroboros/Animation/Anim.h
- Editor/src/Ouroboros/Animation/Anim_Utils.cpp
- Editor/src/Ouroboros/Animation/Anim_Utils.h
- Editor/src/Ouroboros/Animation/AnimationComponent.h
- Editor/src/Ouroboros/Animation/AnimationInternal.cpp
- Editor/src/Ouroboros/Animation/AnimationInternal.h
- Editor/src/Ouroboros/Animation/AnimationSkeleton.cpp
- Editor/src/Ouroboros/Animation/AnimationSkeleton.h
- Editor/src/Ouroboros/Animation/AnimationSystem.cpp
- Editor/src/Ouroboros/Animation/AnimationTimeline.cpp
- Editor/src/Ouroboros/Animation/AnimationTimeline.h
- Editor/src/Ouroboros/Animation/AnimationTracker.h
- Editor/src/Ouroboros/Animation/AnimationTree.cpp
- Editor/src/Ouroboros/Animation/AnimationTree.h
- Editor/src/Ouroboros/Vulkan/SkinRendererSystem.cpp
set it to blend for 0.15s of the beginning of an animation
handle transitions that happen in the middle of transitions for quick blend
> quick blend for animations

- Editor/vendor/physx/Physics/Source/phy.cpp
- Editor/vendor/physx/Physics/Source/phy.h
warnings on return for all paths / enum / noexcept
> fix physics warnings

- .gitignore
- Editor/src/App/Editor/UI/Object Editor/Inspector.cpp
- Editor/src/Ouroboros/Animation/AnimationSkeleton.h
- Editor/src/Ouroboros/Transform/TransformSystem.cpp
- Editor/src/Ouroboros/UI/UISystem.cpp
- Editor/src/Ouroboros/UI/UISystem.h
- Editor/src/Project.cpp
- Editor/vendor/vulkan/OO_Vulkan/src/VulkanRenderer.cpp
- Editor/vendor/vulkan/OO_Vulkan/src/renderpass/ForwardUIPass.cpp
- Editor/vendor/vulkan/vendor/msdf-atlas-gen/RectanglePacker.cpp
- Editor/vendor/vulkan/vendor/msdf-atlas-gen/TightAtlasPacker.cpp
> gitignore minutesetup, warning fixes, removed tracy for final build

- Editor/src/Ouroboros/API/RigidbodyAPI.h
- Editor/src/Project.cpp
- Editor/vendor/scriptcore/src/ScriptCore/Components/Rigidbody.cs
- added missing C# physics stuff
- fixed sln and csproj regenerating for exe
> Scripting Update

- Editor/src/Ouroboros/Core/Input.h
for more precise player control
> Updated Controller Deadzone

- Editor/src/Ouroboros/Scene/RuntimeScene.cpp
- Editor/src/Ouroboros/Scripting/ScriptSystem.cpp
- Editor/src/Ouroboros/Scripting/ScriptSystem.h
- Editor/vendor/scripting/src/Scripting/ScriptDatabase.cpp
- Editor/vendor/scripting/src/Scripting/ScriptDatabase.h
actual script deletion now deferred to after C# LateUpdate is called
(tested from Scripting branch, cant really test with main right now due to crashes, but should work)
> Fixed script deletion bug

- Editor/src/Ouroboros/API/PhysicsAPI.h
- Editor/src/Ouroboros/Physics/PhysicsSystem.cpp
- Editor/src/Ouroboros/Physics/PhysicsSystem.h
- Editor/vendor/physx/Physics/Source/phy.cpp
- Editor/vendor/physx/Physics/Source/phy.h
- Editor/vendor/scriptcore/src/ScriptCore/Components/Rigidbody.cs
additional sweepcast API available to physics
> Physics Sweepcast [merge ONLY after physics revamp is merged!]

- Editor/src/App/Editor/Serializer.cpp
- Editor/src/App/Editor/Serializer.h
- Editor/src/App/Editor/Steam/SteamInterface.cpp
- Editor/src/App/Editor/Steam/SteamInterface.h
- Editor/src/Ouroboros/API/MainAPI.cpp
- Editor/src/Ouroboros/API/SceneManagerAPI.h
- Editor/src/Ouroboros/API/SteamAPI.h
- Editor/src/Ouroboros/Asset/AssetManager.cpp
- Editor/src/Ouroboros/Scene/RuntimeScene.cpp
- Editor/src/Ouroboros/Scripting/ScriptManager.cpp
- Editor/src/Ouroboros/Scripting/ScriptManager.h
- Editor/src/Ouroboros/Scripting/ScriptSystem.cpp
- Editor/src/Ouroboros/Scripting/ScriptSystem.h
- Editor/vendor/scriptcore/src/ScriptCore/Data/LoadProgress.cs
- Editor/vendor/scriptcore/src/ScriptCore/Libraries/SceneManager.cs
- Editor/vendor/scriptcore/src/ScriptCore/Libraries/Steam.cs
- C# functions for steam achievements (no idea if that works)
- C# preloading function so that scenes can actually run while loading (i.e. loading animations can be played)
> C# Loading and Steam Achievements

- Editor/engine_portable.iss
- Editor/engine_portable_debug.iss
- Editor/executable_portable.iss
- Editor/src/App/Editor/Steam/SteamInterface.cpp
- Editor/src/App/Editor/Steam/SteamInterface.h
added a function to check for achivmeent status
> Jun xiang/steam
